### PR TITLE
[Fix] roboError can be null

### LINKED ISSUE #155: Plugin crashing the homebridge installation
From time to time I'm facing this error that shuts down my homebridge (hoobs) server:

`[Homebridge] [4/19/2020, 7:32:09 PM] TypeError: Cannot read property 'id' of null
    at XiaomiRoborockVacuum.changedError (/home/hoobs/.hoobs/node_modules/@hoobs/roborock/index.js:276:78)
    at module.exports.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/roborock/index.js:368:54)
    at EventEmitter.emit (/home/hoobs/.hoobs/node_modules/abstract-things/events/index.js:155:14)
    at Immediate.<anonymous> (/home/hoobs/.hoobs/node_modules/abstract-things/thing.js:141:14)
    at processImmediate (internal/timers.js:456:21)
`
Thanx for your help,

Olivier.

### PR DESCRIPTION
**Pull request by afharo**
Closes #155

### CODE REVIEW

**Comment by nicoh88** [comment]
@afharo You are the man!

You're doing a really great job here. I would be happy if you continued to manage this plugin. Make changes, edit issues and merge pull reqeuests. I'm out. I sign me out of all notifications for this plugin. You are also registered as a collaborator with [miio](https://github.com/nicoh88/miio) and also with both NPM packages.

Good luck und thanks.

**Comment by afharo** [comment]
Thank you @nicoh88 !
I'm sad you are leaving the front line. But I understand! It can be really time consuming.
Before you fully unsubscribe, can you make sure I have the rights to run `npm publish`?
Also, I cannot see the settings tab in this project. I may need it if I want to set any automated actions (hopefully we'll have some unit tests and build process in the future) :)

**Comment by nicoh88** [comment]
I've added you (or a wrong person 🤣). I don't know what I have to do.

Bildschirmfoto 2020-04-21 um 10 51 58
Bildschirmfoto 2020-04-21 um 10 53 16

**Comment by afharo** [comment]
Oh! Cool! Sorry I didn't even check. I assume just because I didn't receive an email from NPM, it was not done. 

I just logged in the NPM site and I can see those packages in "My Packages" list.
Thank you kindly!

**Pull request merged**
