### PR TITLE
Try to support the new WaterBox property

### LINKED ISSUE #79: S5 max - fan speed and mopping modes
Hello,

I configure correctly (I think) the roborock s5 max but the plugin not recognised it. 

this is the log:
homebridgeTLS  | [12/14/2019, 9:51:20 PM] [Roborock S5 Max] ERR getBatteryLow | No vacuum cleaner is discovered yet.
homebridgeTLS  | [12/14/2019, 9:51:20 PM] [Roborock S5 Max] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
homebridgeTLS  | [12/14/2019, 9:51:20 PM] [Roborock S5 Max] ERR getDevice | Is not a vacuum cleaner!

the config is the following:

        {
            "name": "Roborock",
            "ip": "192.168.2.124",
            "token": "xxxx767358306974534263584747xxxx",
            "pause": true,
            "dock": true,
            "accessory": "XiaomiRoborockVacuum"
        }

### PR DESCRIPTION
**Pull request by afharo**
Fixes #79 

Trying to support the water box mode in S5 Max.

@infernalK I'd appreciate it if you can test these changes on your end by installing it from this branch in git.

### CODE REVIEW

**Comment by infernalK** [comment]
Thanks, I’ll try this afternoon. Can you give me command line to install, sorry I’m new with this.

**Comment by nicoh88** [comment]
@infernalK 

```
sudo su -
npm install -g afharo/homebridge-xiaomi-roborock-vacuum#s5-max
```

**Comment by infernalK** [comment]
I can't install :

pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# npm install -g afharo/homebridge-xiaomi-roborock-vacuum#s5-max
npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b s5-max git://github.com/afharo/homebridge-xiaomi-roborock-vacuum.git /root/.npm/_cacache/tmp/git-clone-656a1679
npm ERR! fatal: impossible de créer les répertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-656a1679': Permission non accordée
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-01T16_29_26_172Z-debug.log
root@raspberrypi:/home/pi#

**Comment by nicoh88** [comment]
`sudo su -`

`

**Comment by infernalK** [comment]
Thanks I missed the -

I have an other problem

[2020-2-1 6:04:20 PM] [Aspirateur] Initializing XiaomiRoborockVacuum accessory...
[2020-2-1 6:04:20 PM] Error: Cannot add a Service with the same UUID '00000040-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:152:15)
    at /usr/lib/node_modules/homebridge/lib/server.js:471:19
    at Array.forEach (<anonymous>)
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:451:14)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:309:26)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[2020-2-1 6:04:20 PM] Got SIGTERM, shutting down Homebridge...
homebridge@1.service: Main process exited, code=exited, status=143/n/a
homebridge@1.service: Failed with result 'exit-code'.

**Comment by infernalK** [comment]
Hello, 
It seems to work. I will test more this evening or tomorrow.

**Comment by afharo** [comment]
Oops! Sorry! It should be fixed now... Please, bear in mind the new config flag (unfortunately `homebridge` does not support dynamic services 😖 )

**Comment by infernalK** [comment]
Hi,
fan speed is OK
waterbox mode doesn't work

[2020-2-3 8:39:53 AM] [Aspirateur] INF getWaterSpeed | roborock.vacuum.s5e | WaterBoxMode is undefined over miIO. Converting to HomeKit


[2020-2-3 9:40:27 AM] [Aspirateur] ACT setWaterSpeed | roborock.vacuum.s5e | WaterBoxMode set to 203 over miIO for "Hight".
Mon, 03 Feb 2020 08:40:27 GMT EventedHTTPServer [::ffff:192.168.1.95] HTTP Response is finished
Mon, 03 Feb 2020 08:40:27 GMT EventedHTTPServer [::ffff:192.168.1.95] HTTP request: /characteristics
Mon, 03 Feb 2020 08:40:27 GMT HAPServer [0E:D8:45:84:7D:DB] HAP Request: PUT /characteristics
Mon, 03 Feb 2020 08:40:27 GMT Accessory [Homebridge@1] Processing characteristic set: [{"aid":4,"iid":48,"value":100}]
Mon, 03 Feb 2020 08:40:27 GMT Accessory [Homebridge@1] Setting Characteristic "Rotation Speed" to value 100
[2020-2-3 9:40:27 AM] [Aspirateur] ACT setWaterSpeed | roborock.vacuum.s5e | WaterBoxMode set to 203 over miIO for "Hight".
Mon, 03 Feb 2020 08:40:27 GMT EventedHTTPServer [::ffff:192.168.1.95] HTTP Response is finished
Mon, 03 Feb 2020 08:40:30 GMT EventedHTTPServer [::ffff:192.168.1.95] Sending HTTP event '3.10' with data: {"characteristics":[{"aid":3,"iid":10,"value":39.4}]}
Mon, 03 Feb 2020 08:40:35 GMT EventedHTTPServer [::ffff:192.168.1.95] Sending HTTP event '3.10' with data: {"characteristics":[{"aid":3,"iid":10,"value":37.9}]}
2020-02-03T08:40:45.559Z thing:miio:321712207 -> (5) {"method":"get_status","params":[],"id":14}
2020-02-03T08:40:45.560Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 13 2c f0 4f 5e 37 dc 8c b6 41 5d 90 25 34 f6 ba c4 b6 00 40 13 18 b0 55>
2020-02-03T08:40:45.561Z thing:miio:321712207 -> (5) {"method":"get_consumable","params":[],"id":15}
2020-02-03T08:40:45.561Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 13 2c f0 4f 5e 37 dc 8c ef 8b da 9a 1f db 31 90 04 ed 0a 19 36 7a f6 8f>
2020-02-03T08:40:45.569Z miio:packet <- <Buffer 21 31 01 b0 00 00 00 00 13 2c f0 4f 5e 37 dc 8d ff ce 94 29 82 d9 3c 61 4b c7 41 cb 47 d4 9b ab>
2020-02-03T08:40:45.570Z miio:packet <- <Buffer 21 31 01 b0 00 00 00 00 13 2c f0 4f 5e 37 dc 8d ff ce 94 29 82 d9 3c 61 4b c7 41 cb 47 d4 9b ab>
2020-02-03T08:40:45.571Z thing:miio:321712207 <- Message: `{"result":[{"msg_ver":2,"msg_seq":1588,"state":8,"battery":93,"clean_time":1683,"clean_area":26005000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":1,"water_box_status":1,"fan_power":104,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":201,"water_box_carriage_status":1,"mop_forbidden_enable":1}],"id":14}`
2020-02-03T08:40:45.571Z miio:packet <- <Buffer 21 31 00 d0 00 00 00 00 13 2c f0 4f 5e 37 dc 8d 5c b7 98 37 07 28 27 7d 3b d0 4c 3d 55 c6 56 8c>
2020-02-03T08:40:45.572Z miio:packet <- <Buffer 21 31 00 d0 00 00 00 00 13 2c f0 4f 5e 37 dc 8d 5c b7 98 37 07 28 27 7d 3b d0 4c 3d 55 c6 56 8c>
2020-02-03T08:40:45.572Z thing:miio:321712207 <- Message: `{"result":[{"main_brush_work_time":84480,"side_brush_work_time":29761,"filter_work_time":84480,"filter_element_work_time":80494,"sensor_dirty_time":84480}],"id":15}`
Mon, 03 Feb 2020 08:40:50 GMT EventedHTTPServer [::ffff:192.168.1.95] Sending HTTP event '3.10' with data: {"characteristics":[{"aid":3,"iid":10,"value":38.9}]}
Mon, 03 Feb 2020 08:40:55 GMT EventedHTTPServer [::ffff:192.168.1.95] Sending HTTP event '3.10' with data: {"characteristics":[{"aid":3,"iid":10,"value":37.9}]}
Mon, 03 Feb 2020 08:41:00 GMT EventedHTTPServer [::ffff:192.168.1.95] Sending HTTP event '3.10' with data: {"characteristics":[{"aid":3,"iid":10,"value":39.4}]}

**Comment by afharo** [comment]
@infernalK thank you for your feedback. As expected, the _naive_ approach of simply overwriting the value of the property didn't work out, unfortunately (but you gotta try, right? 😅).

I'll do some research to find out if there's any special command we can use to change the property.
Help is appreciated 😉

**Comment by infernalK** [comment]
I found this :  "set_water_box_custom_mode"

https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/water_box_custom_mode.md

**Comment by afharo** [comment]
Oh! Wow! Thanks for finding that git repo! Bookmarking it right now!
Pushed some changes to see if it works now 🤞

**Comment by infernalK** [comment]
Status reading is a bit stange may the get need a change also

[2020-2-3 2:14:04 PM] [Aspirateur] INF getWaterSpeed | roborock.vacuum.s5e | WaterBoxMode is undefined over miIO. Converting to HomeKit

The set does something I hear the robot "bip" but value is not set

2020-02-03T13:35:01.731Z thing:miio:321712207 Property water_box_mode changed from 201 to 202
Mon, 03 Feb 2020 13:35:01 GMT Accessory [Homebridge@1] Error setting Characteristic "Rotation Speed" to value 59:  r is not defined
Mon, 03 Feb 2020 13:35:01 GMT Accessory [Homebridge@1] Processing characteristic set: [{"aid":4,"iid":48,"value":76}]
Mon, 03 Feb 2020 13:35:01 GMT Accessory [Homebridge@1] Setting Characteristic "Rotation Speed" to value 76
[2020-2-3 2:35:01 PM] [Aspirateur] ACT setWaterSpeed | roborock.vacuum.s5e | WaterBoxMode set to 203 over miIO for "Hight".
2020-02-03T13:35:01.844Z thing:miio:321712207 -> (5) {"method":"set_water_box_custom_mode","params":[203],"id":96}
2020-02-03T13:35:01.845Z miio:packet -> <Buffer 21 31 00 60 00 00 00 00 13 2c f0 4f 5e 38 21 85 ed ff d9 6a f5 e2 f8 b6 90 35 10 d1 41 e5 88 3a>
2020-02-03T13:35:01.852Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 13 2c f0 4f 5e 38 21 85 fc 16 7e 3b 44 a4 0a 37 4d 97 ff 11 e2 4e 6a 5f>
2020-02-03T13:35:01.852Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 13 2c f0 4f 5e 38 21 85 fc 16 7e 3b 44 a4 0a 37 4d 97 ff 11 e2 4e 6a 5f>
2020-02-03T13:35:01.852Z thing:miio:321712207 <- Message: `{"result":["ok"],"id":96}`
2020-02-03T13:35:01.903Z thing:miio:321712207 -> (5) {"method":"get_status","params":[],"id":97}
2020-02-03T13:35:01.904Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 13 2c f0 4f 5e 38 21 85 fa c7 f0 3e a5 8d bd 9c f3 6f 32 2e 24 e1 89 91>
2020-02-03T13:35:01.904Z thing:miio:321712207 -> (5) {"method":"get_consumable","params":[],"id":98}
2020-02-03T13:35:01.905Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 13 2c f0 4f 5e 38 21 85 82 a3 62 68 1c 8b 06 6c f6 17 da 6c 2a 78 68 71>
2020-02-03T13:35:01.917Z miio:packet <- <Buffer 21 31 01 a0 00 00 00 00 13 2c f0 4f 5e 38 21 85 2b e1 7d c5 5f e5 e5 25 7e b0 b1 f3 c5 32 f1 06>
2020-02-03T13:35:01.917Z miio:packet <- <Buffer 21 31 01 a0 00 00 00 00 13 2c f0 4f 5e 38 21 85 2b e1 7d c5 5f e5 e5 25 7e b0 b1 f3 c5 32 f1 06>
2020-02-03T13:35:01.917Z thing:miio:321712207 <- Message: `{"result":[{"msg_ver":2,"msg_seq":2437,"state":8,"battery":100,"clean_time":3,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":1,"water_box_status":1,"fan_power":102,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":203,"water_box_carriage_status":1,"mop_forbidden_enable":1}],"id":97}`
2020-02-03T13:35:01.918Z miio:packet <- <Buffer 21 31 00 d0 00 00 00 00 13 2c f0 4f 5e 38 21 85 16 a0 d7 c8 fb c1 87 34 6e 48 e5 ab d0 bc 62 81>
2020-02-03T13:35:01.918Z miio:packet <- <Buffer 21 31 00 d0 00 00 00 00 13 2c f0 4f 5e 38 21 85 16 a0 d7 c8 fb c1 87 34 6e 48 e5 ab d0 bc 62 81>
2020-02-03T13:35:01.919Z thing:miio:321712207 <- Message: `{"result":[{"main_brush_work_time":86296,"side_brush_work_time":31577,"filter_work_time":86296,"filter_element_work_time":82310,"sensor_dirty_time":86296}],"id":98}`
2020-02-03T13:35:01.919Z thing:miio:321712207 Property water_box_mode changed from 202 to 203
Mon, 03 Feb 2020 13:35:01 GMT Accessory [Homebridge@1] Error setting Characteristic "Rotation Speed" to value 76:  r is not defined

**Comment by afharo** [comment]
Thanks! I changed it now to read the property by using the actual method (from the docs you shared). It should work better now.

**Comment by infernalK** [comment]
Thanks it works perfectly

**Comment by afharo** [comment]
Thank you for testing!

**Comment by infernalK** [comment]
You’re welcome. If you need help for other test I’ll be happy to help

**Comment by nicoh88** [comment]
@afharo Can i merge?

**Comment by afharo** [comment]
@nicoh88 I think so. According to @infernalK it's all good :)

Do you think I should change anything in the implementation? Maybe some methods belong in the `miio` library itself, but I think I'll move them sometime in the future.

**Comment by nicoh88** [comment]
**Successfully published homebridge-xiaomi-roborock-vacuum@0.6.7**

```
sudo su -
npm -g install homebridge-xiaomi-roborock-vacuum@latest
```

**Pull request merged**
