### PR TITLE
Refresh the state every 30s to ensure miio is still properly connected

### PR DESCRIPTION
**Pull request by afharo**
Related to #68

### CODE REVIEW

**Comment by nicoh88** [comment]
Test with: `npm install -g nicoh88/homebridge-xiaomi-roborock-vacuum#master`

**Comment by nicoh88** [comment]
Doesn't work.

**#master**

- Gen1 (Mi Robot) works, but `` not
- Gen2 (Roborock S50) doesn't works

```
[2020-1-17 21:04:53] [Staubsauger OG Bad] DEB ensureDevice | rockrobo.vacuum.v1 | The socket is still on. Reusing it.
[2020-1-17 21:04:53] [Staubsauger OG Bad] DEB getState | rockrobo.vacuum.v1 | State {"batteryLevel":100,"charging":true,"cleaning":false,"fanSpeed":90}
[2020-1-17 21:04:53] [Staubsauger OG Bad] MON changedCleaning | rockrobo.vacuum.v1 | CleaningState is now false
[2020-1-17 21:04:53] [Staubsauger OG Bad] INF changedCleaning | rockrobo.vacuum.v1 | Cleaning is OFF.
[2020-1-17 21:04:53] [Staubsauger OG Bad] MON changedCharging | rockrobo.vacuum.v1 | ChargingState is now true
[2020-1-17 21:04:53] [Staubsauger OG Bad] INF changedCharging | rockrobo.vacuum.v1 | Charging is active
[2020-1-17 21:04:53] [Staubsauger OG Bad] INF changedCharging | rockrobo.vacuum.v1 | Robot was docked.
[2020-1-17 21:04:53] [Staubsauger OG Bad] MON changedSpeed | rockrobo.vacuum.v1 | FanSpeed is now 90%
[2020-1-17 21:04:53] [Staubsauger OG Bad] INF changedSpeed | rockrobo.vacuum.v1 | Speed was changed to 90% (Max), for HomeKit 100%
[2020-1-17 21:04:53] [Staubsauger OG Bad] DEB changedBattery | rockrobo.vacuum.v1 | BatteryLevel undefined%
```

```
[2020-1-17 21:04:53] [Staubsauger EG Flur] DEB ensureDevice | roborock.vacuum.s5 | The socket is still on. Reusing it.
[2020-1-17 21:04:53] [Staubsauger EG Flur] DEB changedError | roborock.vacuum.s5 | ErrorID: charger-offline, ErrorDescription: Charger is offline
[2020-1-17 21:04:53] [Staubsauger EG Flur] WAR changedError | roborock.vacuum.s5 | Robot has an ERROR - charger-offline, Charger is offline
[2020-1-17 21:04:53] [Staubsauger EG Flur] ERR getState | this.device.state | [object Object]
```

**latest npm**

- Gen1 (Mi Robot) works
- Gen2 (Roborock S50) works

```
Jan 17 21:15:12 frida homebridge[5493]: [2020-1-17 21:15:12] [Staubsauger OG Bad] DEB ensureDevice | rockrobo.vacuum.v1 | The socket is still on. Reusing it.
Jan 17 21:15:12 frida homebridge[5493]: [2020-1-17 21:15:12] [Staubsauger OG Bad] DEB ensureDevice | rockrobo.vacuum.v1 | The socket is still on. Reusing it.
Jan 17 21:15:12 frida homebridge[5493]: [2020-1-17 21:15:12] [Staubsauger EG Flur] INF getCleaning | roborock.vacuum.s5 | Cleaning is false
Jan 17 21:15:12 frida homebridge[5493]: [2020-1-17 21:15:12] [Staubsauger EG Flur] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO. Converting to HomeKit
Jan 17 21:15:12 frida homebridge[5493]: [2020-1-17 21:15:12] [Staubsauger EG Flur] INF getSpeed | roborock.vacuum.s5 | Fanspeed is 100 over miIO "Max" > HomeKit speed 100%
Jan 17 21:15:12 frida homebridge[5493]: [2020-1-17 21:15:12] [Staubsauger EG Flur] INF getBatteryLow | roborock.vacuum.s5 | Batterylevel is 82%
Jan 17 21:15:12 frida homebridge[5493]: [2020-1-17 21:15:12] [Staubsauger OG Bad] INF getCleaning | rockrobo.vacuum.v1 | Cleaning is false
Jan 17 21:15:12 frida homebridge[5493]: [2020-1-17 21:15:12] [Staubsauger OG Bad] INF getSpeed | rockrobo.vacuum.v1 | Fanspeed is 90 over miIO. Converting to HomeKit
Jan 17 21:15:12 frida homebridge[5493]: [2020-1-17 21:15:12] [Staubsauger OG Bad] INF getSpeed | rockrobo.vacuum.v1 | Fanspeed is 90 over miIO "Max" > HomeKit speed 100%
Jan 17 21:15:12 frida homebridge[5493]: [2020-1-17 21:15:12] [Staubsauger OG Bad] INF getBatteryLow | rockrobo.vacuum.v1 | Batterylevel is 100%
```

**Comment by afharo** [comment]
Sorry, I had this PR marked as `Draft` to test it from my branch before getting it merged.

Re your error, it's weird, it is working for my Roborock S50:
```
0|Homebrid | [1/17/2020, 10:38:28 PM] [Roberta] DEB ensureDevice | roborock.vacuum.s5 | The socket is still on. Reusing it.
0|Homebrid | [1/17/2020, 10:38:28 PM] [Roberta] DEB getState | roborock.vacuum.s5 | State {"batteryLevel":100,"charging":true,"cleaning":false,"fanSpeed":60}
0|Homebrid | [1/17/2020, 10:38:28 PM] [Roberta] MON changedCleaning | roborock.vacuum.s5 | CleaningState is now false
0|Homebrid | [1/17/2020, 10:38:28 PM] [Roberta] INF changedCleaning | roborock.vacuum.s5 | Cleaning is OFF.
0|Homebrid | [1/17/2020, 10:38:28 PM] [Roberta] MON changedCharging | roborock.vacuum.s5 | ChargingState is now true
0|Homebrid | [1/17/2020, 10:38:28 PM] [Roberta] INF changedCharging | roborock.vacuum.s5 | Charging is active
0|Homebrid | [1/17/2020, 10:38:28 PM] [Roberta] INF changedCharging | roborock.vacuum.s5 | Robot was docked.
0|Homebrid | [1/17/2020, 10:38:28 PM] [Roberta] MON changedSpeed | roborock.vacuum.s5 | FanSpeed is now 60%
0|Homebrid | [1/17/2020, 10:38:28 PM] [Roberta] INF changedSpeed | roborock.vacuum.s5 | Speed was changed to 60% (Balanced), for HomeKit 60%
0|Homebrid | [1/17/2020, 10:38:28 PM] [Roberta] DEB changedBattery | roborock.vacuum.s5 | BatteryLevel undefined%
0|Homebrid | [1/17/2020, 10:38:28 PM] [Roberta] MON changedPause | roborock.vacuum.s5 | CleaningState is now false
0|Homebrid | [1/17/2020, 10:38:28 PM] [Roberta] INF changedPause | roborock.vacuum.s5 | Paused not possible, no cleaning
```

**Comment by afharo** [comment]
I'm not calling any new method. I'm simply invoking it every 30s instead of doing so only at the beginning like we do in the NPM version.

**Comment by nicoh88** [comment]
> Sorry, I had this PR marked as `Draft` to test it from my branch before getting it merged.

Uhh, my mistake.

**Pull request merged**
